# Tendencias e Innovacion en Tecnologia Agricola (TEA)
tipodeDatos = input("Qué tipos de datos sale en la consola 1.2.1 ? ")
print(tipodeDatos)
tipodeDatos = input("Qué tipo de datos sale en la consola 1.2.2 ? ")
print(tipodeDatos)
tipodeDatos = input("Qué tipos de datos sale en la consola 1.2.3 ? ")
print(tipodeDatos)
nombrecompleto = input ("Cuál es tu nombre completo ? ")
print(nombrecompleto)
correo = input ("Cuál es su correo ? ")
print(correo)
dirección = input ("Cuál es la dirección de su repositorio de código fuente ? ")
print(dirección)
